document.title = 'Radar de Tecnologia'






// store data inline directly as a table...


const rawDataTable = [



['name', 'ring', 'quadrant', 'type', 'description'],
['Integração como código', 'adotar', 'técnicas', 's1', 'Times almejam a automação para passar o código através dos ambientes, incluindo na infraestrutura de desenvolvimento. Infraestrutura como Código permite que isso seja feito não somente definindo uma rotina, mas fazendo isso de forma automática. Ex.:<a href="https://github.com/SpringerSBM/gomatic">GoMatic</a>.'],
['API como produto', 'experimentar', 'técnicas', 's1', 'Times que constroem APIs deveriam entender a necessidade dos seus clientes e tornar o produto atrativo para eles. Testes de usabilidade e pesquisa de UX podem levar a um melhor design e entendimento de padrões de uso da API, ajudando a trazer um pensamento de produto para APIs. APIs, assim como produtos, devem ser ativamente mantidas, ter suporte e serem fáceis de usar. Elas devem ter um dono que defende seus usuários e caminha em direção à melhoria contínua. Em nossa experiência, pensamento de produto é o ingrediente que falta e faz toda a diferença entre uma integração qualquer e um negócio ágil construído em cima de uma plataforma de APIs.'],
['Guardar segredos fora do código', 'experimentar', 'técnicas', 's4', 'Maneira de lembrar as tecnologistas que existem outras opções para armazenar segredos. Por exemplo, HashiCorp Vault, servidores de CI e ferramentas de gerenciamento de configuração fornecem mecanismos para armazenar segredos que não são vinculados ao código-fonte de uma aplicação. Ambas as abordagens são viáveis e recomendamos que você use pelo menos uma delas em seus projetos.'],
['Hospedar dados PII na EU', 'experimentar', 'técnicas', 's4', 'Em um grande número de países, há governos tentando acessar informações privadas identificáveis (Personally Identifiable Information - PII). O aumento do número de soluções na nuvem torna mais difícil a proteção desses dados. A União Europeia tem algumas das mais progressivas leis de privacidade e é a escolha de local para servidores de muitas empresas, como Amazon, Google e Microsoft.'],
['Legado em um pacote', 'experimentar', 'técnicas', 's4', 'Trabalhar com código legado, especialmente com grandes monólitos, é uma das experiências mais insatisfatórias e desgastantes para quem desenvolve. Apesar da nossa sugestão contra extender e ativamente manter monólitos legados, eles continuam a ser dependências em nossos ambientes e as pessoas desenvolvedoras muitas vezes subestimam o custo e o tempo necessários para desenvolver junto dessas dependências. Para ajudar a reduzir o desgaste, usamos imagens de máquinas virtuais ou imagens de contêiner com Docker para criar imagens imutáveis de sistemas legados e suas configurações. A intenção é manter o LEGADO ENCAIXOTADO para ser executado localmente, removendo a necessidade de reconstruir, reconfigurar ou compartilhar ambientes. Em um cenário ideal, os times que possuem sistemas legados geram as imagens legadas por meio de seus pipelines de compilação, e as pessoas que desenvolvem podem executar e orquestrar essas imagens em seus sandboxes alocados com mais confiabilidade. Embora essa abordagem tenha reduzido o tempo total gasto por cada pessoa desenvolvedora, o sucesso foi limitado quando times que são donos das dependências do legado relutaram em criar imagens de contêiner para uso de outras pessoas'],
['Registro leve de Decisões de Arquitetura', 'experimentar', 'técnicas', 's1', 'Mesmo que muito da documentação pode ser substituído por código bem feito e testes, é importante em um mundo de arquitetura evolucionária manter certas decisões de design a fim de beneficiar os times futuros. Registro leve de Decisões de Arquitetura é uma técnica para capturar importantes decisões de arquitetura juntamente com seu contexto e consequências. Embora esse tipo de informação seja normalmente armazenada em forma de wiki, normalmente preferimos guardá-las em um controle de versões.'],
['Aplicações Web Progressivas', 'experimentar', 'técnicas', 's2', 'O aumento de APLICAÇÕES WEB PROGRESSIVAS (PWAs) é a última tentativa de recuperar a web móvel como resposta ao "desgaste" com aplicativos dos usuários. Originalmente propostas pelo Google em 2015, PWAs são aplicações web que usam as mais recentes tecnologias para combinar o melhor da web e aplicações móveis nativas. Usando um conjunto de tecnologias padrão abertas, como service workers, app manifest e cache e push APIs, podemos criar aplicações independentes da plataforma e oferecer experiências de usuário semelhantes às dos aplicativos. Isso traz paridade para aplicações web e nativas e ajuda quem desenvolve para dispositivos móveis a atingir usuários além dos limites impostos pelas lojas de aplicativos. Pense em PWAs como sites que agem e sentimos como aplicativos nativos.'],
['Prototipar com InVision e Sketch', 'experimentar', 'técnicas', 's2', 'O uso combinado de InVision e Sketch alterou a forma como algumas pessoas abordam o desenvolvimento de aplicações web. Embora sejam ferramentas, é a técnica de PROTOTIPAGEM COM INVISION E SKETCH que realmente torna este blip significativo. Criar protótipos ricos e clicáveis como ponto de partida para implementar o comportamento de front-end e back-end ajuda a acelerar o desenvolvimento e elimina o atrito nos detalhes de implementação. O uso combinado dessas ferramentas atinge o equilíbrio certo entre a elaboração prematura dos detalhes visuais e a antecipação de feedback dos usuários sobre a experiência interativa.'],
['Arquitetura sem Servidor', 'experimentar', 'técnicas', 's1', 'A abordagem de ARQUITETURA SEM SERVIDOR substitui máquinas virtuais de longa duração por poder computacional efêmero, que passa a existir sob solicitação e desaparece imediatamente após o uso. Nossos times gostam da abordagem sem servidor; tem funcionado bem para nós e a consideramos uma escolha de arquitetura válida. Observe que a abordagem sem servidor não precisa ser tudo ou nada: alguns de nossos times implantaram uma parte de seus sistemas sem servidor embora tenham mantido uma abordagem tradicional de arquitetura para outras partes. Ainda que AWS Lambda seja quase um sinônimo de sem servidor, todos os demais grandes provedores de nuvem têm ofertas similares, e recomendamos ainda avaliar opções de nicho como webtask.'],
['Query direcionada ao cliente', 'avaliar', 'técnicas', 's1', 'Embora alguns problemas que as pessoas encontram com serviços RESTful possam ser atribuídos a RESTs incompletos, há casos em que o ponto crítico é outro. Quando as querys feitas diretamente pelo cliente, eles têm mais controle sobre o conteúdo e a quantidade dos dados retornados. Isso coloca mais responsabilidade na camada de serviços e pode levar a benefícios se essa técnica for bem empregada. Vale a pena explorar mais caso RESTful APIs bem modeladas não estão funcionando bem.'],
['Verificação de segurança de container', 'avaliar', 'técnicas', 's1', 'A revolução dos containers estimulada pelo Docker reduziu drasticamente a fricção na movimentação de aplicações entre ambientes mas, ao mesmo tempo, criou um buraco no método tradicional de decidir o que vai para a produção. O próprio Docker provê <a href="https://blog.docker.com/2016/05/docker-security-scanning/">algumas ferramentas de scan</a> para validação.'],
['APIs de Conversação', 'avaliar', 'técnicas', 's2', 'APIS APTAS PARA CONVERSAÇÃO podem ser um exemplo do padrão back-end para front-end, no qual o front-end é uma plataforma de bate-papo. Esse tipo de API pode lidar com os detalhes desse estilo de interação ao gerenciar estados de conversação enquanto chama os serviços subjacentes em nome do front-end de voz.'],
['Privacidade Diferenciada', 'avaliar', 'técnicas', 's1', 'Já é conhecido que os pacotes de dados anônimos podem revelar identidades sobre indivíduos, principalmente quando os dados são cruzados. Com o aumento da preocupação em relação à privacidade, algumas companhias estão adotando diferentes técnicas de privacidade para aumenta-lá em relação ao indivíduo, enquanto tentam maximizar a precisão e o resultado das buscas estatísticas nos grandes bancos de dados. Para atingir esse objetivo, pode ser introduzida uma pequena quantidade de "ruído" nos dados, mas é importante notar que esta ainda é uma área de pesquisas. Continuamos recomendando Datensparsamkeit como uma alternativa: guardar poucos dados faz com que você tenha um índice maior de privacidade.'],
['Micro FrontEnds', 'avaliar', 'técnicas', 's1', 'Já vimos um grande benefício na adoção da <a href="https://www.thoughtworks.com/radar/techniques/microservices">arquitetura de microsserviços</a>, que permitiu o time a escalar a entrega independente dos serviços entregues ou mantidos. Nessa abordagem uma aplicação web é dividida em páginas e funcionalidades e cada uma é desenvolvida por um único time. Muitas técnicas existem para unir todas essas partes para entregar uma experiência de usuário coerente, mas o objetivo é que cada pedaço possa ser desenvolvido, testado e entregue de forma independente. Veja por exemplo <a href="https://www.thoughtworks.com/radar/techniques/bff-backend-for-frontends">BFF - backend for frontends</a>.'],
['Times de engenheiros de plataforma', 'avaliar', 'técnicas', 's2', 'A adoção de nuvem e DevOps, embora tenha aumentado a produtividade dos times, que agora podem agir de forma mais rápida com dependência reduzida em equipes de operações e infraestrutura centralizadas, também restringiu equipes que não possuem habilidades para autogerenciar uma pilha completa de aplicação e operações. Algumas organizações têm abordado este desafio através da criação de TIMES DE PRODUTO DE ENGENHARIA DE PLATAFORMA. Esses times operam uma plataforma interna que permite que times de entrega realizem a implantação e a operação de sistemas com tempo e complexidade reduzidos. A ênfase aqui é em autoserviço por API e ferramentas de suporte, com times de entrega ainda sendo responsáveis por dar suporte ao que eles implantam na plataforma. As organizações que consideram a criação de tal time de plataforma devem ser muito cautelosas para não criar acidentalmente um time de DevOps separado, nem devem simplesmente renomear sua estrutura de hospedagem e operações existente como uma plataforma.'],
['Análise social de código', 'avaliar', 'técnicas', 's2', 'Enriquece nossa compreensão da qualidade do código, sobrepondo o comportamento de uma pessoa desenvolvedora com a análise estrutural do código. Ela usa dados de sistemas de controle de versão, como frequência e tempo de alteração, bem como a pessoa que faz a alteração. Você pode decidir escrever seus próprios scripts para analisar tais dados ou usar ferramentas como CodeScene. CodeScene pode te ajudar a obter uma melhor compreensão de seus sistemas de software, identificando hotspots e subsistemas complexos e difíceis de manter; acoplamento entre subsistemas distribuídos por meio de acoplamento temporal, bem como a visão da lei de Conway na sua organização. Acreditamos que com tendências tecnológicas como sistemas distribuídos, microsserviços e times distribuídos, a dimensão social de nosso código seja vital para a compreensão holística da saúde de nossos sistemas.'],
['Realidade Virtual fora dos jogos', 'avaliar', 'técnicas', 's1', 'A ideia de realidade virtual tem se feito presente por mais de 50 anos, e com sucessivas melhorias da tecnologia computacional, muitas ideias vêm sendo promovidas e exploradas. Acreditamos que agora estamos chegando a um momento decisivo. Headsets orientados ao consumidor chegaram ao mercado no ano passado com preços razoavelmente acessíveis, e placas de vídeo modernas têm poder suficiente para criar experiências imersivas com eles. Os headsets são direcionados principalmente a entusiastas de jogos eletrônicos, mas temos convicção de que eles abrirão muitas oportunidades para a REALIDADE VIRTUAL ALÉM DOS JOGOS. Times sem experiência com criação de jogos não devem subestimar o esforço e a habilidade necessários para criar bons modelos 3D e texturas convincentes.'],
['Instância unificada de integração contínua', 'evitar', 'técnicas', 's1', 'Sentimo-nos novamente na obrigação de alertar contra a criação de uma INSTÂNCIA ÚNICA DE INTEGRAÇÃO CONTÍNUA (CI) PARA TODOS OS TIMES. Embora consolidar e centralizar a infraestrutura de CI seja uma boa ideia na teoria, na prática não enxergamos maturidade suficiente nas ferramentas e produtos nessa área para atingir o resultado esperado. Times de entrega de software que precisam usar a oferta de CI centralizada regularmente têm longos atrasos por dependerem de um time central para executar tarefas de configuração pequenas, ou para resolver problemas na infraestrutura e nas ferramentas compartilhadas. Nesse estágio, continuamos recomendando que as organizações limitem seus investimentos centralizados para estabelecer padrões, orientações e suporte para que times de entrega operem suas próprias infraestruturas de CI.'],
['REST incompleto', 'evitar', 'técnicas', 's1', 'Com a crescente popularidade do <a href="https://www.thoughtworks.com/radar/techniques/bff-backend-for-frontends">BFF - backend for frontends</a> e o uso de frameworks de envio de dados em um único sentido como React.js, notamos uma repercussão na arquitetura do estilo REST. Críticos acusam o REST de causar interações ineficientes entre os sistemas e falhar ao tentar evoluir com o cliente. Ingenuamente desenvolver serviços que expõe modelos de dados estáticos através de URLs pré-estabelecidas resulta em uma implementação incompleta. Em uma arquitetura RESTful completa a abstração de conceitos e eventos são modelados como recursos e a implementação deve fazer uso do hipertexto, links, relações e mídias para maximizar a dissociação dos serviços.'],
['Big Data para tudo', 'evitar', 'técnicas', 's1', 'Continuamos a ver organizações procurando tecnologias interessantes, sem levar em conta escolhas menos complexas e com menos riscos. Um tema em particular é usar sistemas de Big Data distribuídos para pequenos bancos de dados. O banco de dados Apache Cassandra promete uma grande escalabilidade mas já vimos times tomados por sua complexidade arquitetural e operacional.'],
['Falsa Integração Contínua', 'evitar', 'técnicas', 's2', 'Há muito tempo defendemos o uso de Integração Contínua (CI), e tivemos um papel pioneiro na criação de programas para servidores de CI que compilam projetos nos check-ins automaticamente. Quando bem utilizados, esses programas são executados como um processo daemon em uma linha principal compartilhada do projeto que as pessoas desenvolvedoras se comprometem a atualizar diariamente com suas modificações. O servidor de CI compila o projeto e executa testes abrangentes para garantir que todo o sistema de software esteja integrado e sempre em um estado pronto para lançamento, satisfazendo assim os princípios da entrega contínua. Infelizmente, muitas pessoas simplesmente configuram um servidor de CI e erroneamente assumem que estão "fazendo CI", quando na realidade estão perdendo todos os seus benefícios. Os modos de falha comuns incluem: executar CI em uma linha principal compartilhada mas com commits pouco frequentes, de forma que a integração não é realmente contínua; executar uma compilação com cobertura de teste ruim; permitir que a compilação fique em vermelho por longos períodos de tempo; ou executar CI fora da linha principal (em feature-branches), resultando em isolamento contínuo. Mesmo fazendo com que as pessoas se sintam bem, o "CI DE FAZ DE CONTA" que se segue falharia em qualquer teste de certificação de CI confiável.'],
['Ambiente de testes únicos para uma empresa', 'evitar', 'técnicas', 's2', 'Quando as implantações trimestrais ou mensais nas empresas eram considerados uma boa prática, era necessário manter um ambiente completo para executar ciclos de teste antes da implantação em produção. Estes AMBIENTES DE TESTE DE INTEGRAÇÃO EMPRESARIAIS (muitas vezes referidos como SIT ou Staging) são um gargalo comum para a entrega contínua hoje em dia. Os ambientes em si são frágeis e caros de se manter, muitas vezes com componentes que precisam de configuração manual por uma equipe de gerenciamento de ambiente separada. O teste nesse ambiente fornece feedback pouco confiável e lento, e o esforço do teste é duplicado com o que pode ser realizado em componentes isoladamente. Recomendamos que as organizações criem incrementalmente um caminho independente de componentes-chave para produção. Entre as técnica mais importantes estão os testes de contrato guiados pelo consumidor, o desacoplamento entre publicação e implantação, o foco no tempo médio para a recuperação e os testes em produção.'],
['Geração de Código com base em especificações', 'evitar', 'técnicas', 's2', 'Quando SOAP dominava a indústria de software corporativo, a prática de gerar código de cliente a partir de especificações WSDL era uma prática aceita e até mesmo incentivada. Muitas vezes, infelizmente, o código gerado era complexo, não-testável, difícil de modificar e frequentemente não funcionava em todas as plataformas de implementação. Com o advento do REST, descobrimos ser melhor evoluir clientes de API utilizando o padrão de leitura tolerante para extrair e processar apenas os campos necessários. Recentemente observamos um perturbador retorno aos velhos hábitos com pessoas desenvolvedoras gerando código a partir de especificações de API escritos em Swagger ou RAML, prática que chamamos de GERAÇÃO DE CÓDIGO BASEADA EM ESPECIFICAÇÕES. Embora essas ferramentas sejam muito úteis para conduzir o design de APIs e para extrair documentação, nós advertimos contra o tentador atalho de simplesmente gerar código de cliente diretamente dessas especificações. São grandes as chances de que esse código será difícil de testar e manter.'],
['HSTS', 'adotar', 'plataformas', 's1', '<a href="https://www.owasp.org/index.php/HTTP_Strict_Transport_Security">HTTP Strict Transport Security</a> (HSTS) é agora uma política amplamente adotada que permite que sites se protejam contra ataques de downgrade. Quando um contexto HTTPS sofre um ataque de downgrade, o site passa a utilizar o HTTP, permitindo outra gama de ataques, como "man-in-the-middle". Usando HSTS, o servidor envia um header para o navegador informando que o site só deve ser acessado utilizando HTTPS. Durante a implementação, é necessário verificar todas as funcionalidades, já que uma vez habilitado, quase não há forma de desabilitar o HSTS.'],
['Módulos de Segurança do Linux', 'adotar', 'plataformas', 's1', 'O Princípio do Menor Privilégio nos encoraja a restringir os componentes de software para acessarem apenas os recursos de que precisam. Por padrão, no entanto, um processo Linux pode fazer qualquer coisa que seu usuário em execução pode fazer—desde a conexão com portas arbitrárias até a criação de novos shells. O framework MÓDULOS DE SEGURANÇA DO LINUX (LSM), que permite que extensões de segurança sejam conectadas ao kernel, tem sido usado para implementar controle de acesso obrigatório no Linux. SELinux e AppArmor são as implementações predominantes e mais conhecidas compatíveis com LSM que acompanham o kernel. Recomendamos que os times aprendam a usar um desses frameworks de segurança (e é por isso que o colocamos em Adote). Eles ajudam os times a avaliar questões sobre quem tem acesso a quais recursos em servidores compartilhados, incluindo serviços internos. Essa abordagem conservadora para o gerenciamento de acesso ajudará os times a construir segurança em seus processos no ciclo de desenvolvimento de software.'],
['Apache Mesos', 'experimentar', 'plataformas', 's1', 'Nós continuamos tendo experiências positivas utilizando a plataforma <a href="">Apache Mesos</a> para gerenciar clusters em sistemas altamente distribuídos. Mesos gerencia recursos como CPU e armazenamento de forma a aumentar a eficiência enquanto mantém o isolamento.'],
['Auth0', 'experimentar', 'plataformas', 's1', 'Na maioria dos cenários é raramente válido criar seu próprio sistema de autenticação. Utilizar gerenciadores de identidade já criados e testados tentem a aumentar a produtividade e reduzir as vulnerabilidades e os erros. <a href="https://auth0.com/">Auth0</a> nos impressionou por ser de fácil integração, quantidade de protocolos e conectores além de uma rica API de administração.'],
['AWS Device Farm', 'experimentar', 'plataformas', 's2', 'O grande número de dispositivos móveis torna quase impossível para empresas testarem seus aplicativos móveis em todos eles. É aí que entra o AWS DEVICE FARM, um serviço de testes de aplicativos que permite que você execute e interaja com seus aplicativos Android, iOS e web em uma grande variedade de dispositivos físicos hospedados simultaneamente na nuvem. Registros detalhados, gráficos de desempenho e capturas de tela são gerados durante cada execução para fornecer feedback geral e específico do dispositivo. O serviço oferece muita flexibilidade ao permitir que o estado e a configuração de cada dispositivo sejam alterados para reproduzir cenários de teste muito específicos. Nossas equipes estão usando o AWS Device Farm para executar testes de ponta a ponta em dispositivos com a maior base de instalação para seus aplicativos.'],
['AWS Lambda', 'experimentar', 'plataformas', 's1', 'É recomendado que as funções que utilizam <a href="https://aws.amazon.com/lambda/">AWS Lambda</a> contenham quantidades moderadas de código. Tentar estabelecer uma qualidade mínima utilizando grandes funções Lambda é difícil, e a solução pode não ser economicamente viável. Para necessidades mais complexas ainda é recomendada a utilização de containers ou máquinas virtuais.'],
['OpenTracing', 'experimentar', 'plataformas', 's2', 'Enquanto aplicações distribuídas como um único pacote estão sendo quebradas em uma série de microsserviços, traçar rotas entre os múltiplos pontos é necessário. <a href="">OpenTracing</a> está se tornando o padrão ao estabelecer essas ligações. Por enquanto, ele contém suporte para 6 linguagens: Go, JavaScript, Java, Python, Objective-C e C++.'],
['Unity fora dos jogos', 'experimentar', 'plataformas', 's1', 'Depois de anos crescendo como plataforma de desenvolvimento de jogos, <a href="https://unity3d.com/">Unity</a> está se tornando uma plataforma escolhida para desenvolver aplicações tanto no campo da realidade virtual quanto no campo da realidade aumentada. Essa tecnologia pode ser usada para criar programas para as mais variadas plataformas, incluindo Oculus e HTC Vive.'],
['.NET Core', 'avaliar', 'plataformas', 's1', '<a href="https://www.microsoft.com/net/core">.NET Core</a> é um produto modular de código aberto utilizado para criar aplicações que podem ser facilmente portadas para Windows, MacOS e Linux. .NET Core torna possível a criação de programas cross-platform fazendo uso do <a href="http://www.asp.net/core">ASP.NET Core</a> e outras ferramentas, bibliotecas e frameworks. Levando em conta esses fatores, essa plataforma está se tornando altamente popular, construindo uma grande comunidade que só vem a crescer, já que em meados de 2017 a Microsoft lançou a primeira versão estável do .NET Core.'],
['Amazon API Gateway', 'avaliar', 'plataformas', 's1', '<a href="https://aws.amazon.com/api-gateway/">Amazon API Gateway</a> permite que desenvolvedores exponham seus serviços API para a internet. Oferece o usual Gateway de APIs, com ferramentas que incluem gerenciamento de tráfego, autenticação e autorização. É recomendado utilizar este serviço juntamente com o AWS Lambda.'],
['api.ai', 'avaliar', 'plataformas', 's2', 'Paralelamente ao aumento recente de chatbots e plataformas de voz, vimos uma proliferação de ferramentas e plataformas como API.AI, que fornece um serviço para extração de intenção de texto e gerenciamento de fluxo de conversação ao qual você pode se conectar. Recentemente adquirida pelo Google, esta oferta de "compreensão de linguagem natural como um serviço" compete com outras plataformas nessa área, tais como wit.ai e Lex da Amazon.'],
['Cassandra (cuidado)', 'avaliar', 'plataformas', 's1', '<a href="http://cassandra.apache.org/">Cassandra</a> é um sistema de gerenciamento de banco de dados poderoso e escalável, utilizado normalmente para soluções que requerem o armazenamento e processamento de grandes quantidades de dados. Embora tenha várias qualidades, a manutenção e a complexidade fazem com que seu uso só seja recomendado em situações onde o volume de dados é consideravelmente grande.'],
['Compreensão de imagem nas nuvens', 'avaliar', 'plataformas', 's2', 'Compreensão de imagem costumava ser uma arte obscura e exigia uma equipe de cientistas de dados no local. Nos últimos anos, no entanto, estamos mais perto de resolver problemas como classificação/ categorização facial e de imagem, comparações faciais, identificação de marcos faciais e reconhecimento facial. A COMPREENSÃO DE IMAGEM BASEADA NA NUVEM fornece acesso a capacidades de aprendizagem de máquina por meio de serviços como Amazon Rekognition, Microsoft Computer Vision API e a Google Cloud Vision API, que podem complementar os aplicativos de realidade aumentada (RA) e qualquer coisa que envolva rotular e classificar fotos.'],
['DataStax Enterprise Graph', 'avaliar', 'plataformas', 's2', 'Tivemos alguns sucessos iniciais com o DATASTAX ENTERPRISE GRAPH (DSE Graph) para a manipulação de grandes bancos de dados orientados a grafos. Construído em cima do Cassandra, o DSE Graph tem como alvo os grandes conjuntos de dados onde o nosso favorito de longa data, Neo4j, começa a mostrar algumas limitações. Essa escala tem suas compensações; por exemplo, você perde as transações ACID e a natureza livre de esquemas em tempo de execução do Neo4j, mas o acesso às tabelas estruturais do Cassandra, a integração do Spark para cargas de trabalho analíticas e a poderosa linguagem de consulta TinkerPop/Gremlin tornam essa uma opção que vale a pena considerar.'],
['Electron', 'avaliar', 'plataformas', 's1', '<a href="http://electron.atom.io/">Electron</a> é um framework que permite criar aplicações nativas para desktop utilizando tecnologias como HTML, CSS e JavaScript. Os times podem utilizar de membros que têm conhecimento sobre essas tecnologias para criar clientes desktops de forma rápida e elegante.'],
['Ethereum', 'avaliar', 'plataformas', 's1', 'A excitação com blockchain e criptomoedas parece ter atingido seu pico, já que os anúncios de grande impacto nessa área têm sido cada vez mais raros, e é esperado que alguns dos esforços mais especulativos se extingam com o tempo. Um dos blockchains, ETHEREUM apesar de não ser popular entre fãs de blockchain, tem aparecido em cada vez mais iniciativas. Ethereum é um blockchain público com uma linguagem de programação embutida que permite que "contratos inteligentes" sejam criados. Estes são movimentos algorítmicos do "ether" (criptomoeda do Ethereum) em resposta à atividade ocorrendo no blockchain. R3CEV, o consórcio de tecnologia de blockchain para bancos, construiu suas primeiras provas de conceito no Ethereum. O Ethereum foi usado para construir uma Organização Autônoma Distribuída (Distributed Autonomous Organization ou DAO)—uma das primeiras "corporações algorítmicas"—, embora um assalto recente de 150 milhões de dólares em Ether demonstre que blockchain e criptomoedas ainda são o Velho Oeste do mundo da tecnologia.'],
['Hyperledger', 'avaliar', 'plataformas', 's2', 'HYPERLEDGER é uma plataforma construída em torno de tecnologias blockchain. Consiste em uma implementação blockchain chamada Fabric e outras ferramentas associadas. Desconsiderando a excitacão envolvendo blockchain, nossas equipes acharam fácil começar a trabalhar com essas ferramentas. O fato de ser uma plataforma de código aberto apoiada pela Fundação Linux também contribui com a nossa alta expectativa em relação à Hyperledger.'],
['IndiaStack', 'avaliar', 'plataformas', 's1', '<a href="http://www.indiastack.org/">IndiaStack</a> é um grupo de APIs abertas desenvolvido com o objetivo de transformar a India de um país de poucos dados para um país de muitos dados. Um de seus serviços de autenticação é utilizado por mais de um bilhão de indianos.'],
['Kafka Streams', 'avaliar', 'plataformas', 's2', 'KAFKA STREAMS é uma biblioteca leve para a construção de aplicações de streaming. Ela foi projetada com o objetivo de simplificar o processamento de streams o suficiente para torná-lo facilmente acessível como um modelo de programação predominante de aplicativos para serviços assíncronos. Ela pode ser uma boa alternativa para cenários em que você deseja aplicar um modelo de processamento de stream a seu problema sem incluir a complexidade de executar um cluster (geralmente introduzido por estruturas de processamento de stream completos).'],
['Keycloak', 'avaliar', 'plataformas', 's2', 'Em uma arquitetura de microserviços ou qualquer outra arquitetura distribuída, uma das necessidades mais comuns é proteger os serviços ou APIs através de recursos de autenticação e autorização. É aí que a Keycloak entra. KEYCLOAK é uma solução de gerenciamento de acesso e identidade de código aberto que facilita a segurança de aplicativos ou microserviços com pouco ou nenhum código. Ela já vem pronta para uso com suporte para logon único, login social e protocolos padrão, como OpenID Connect, OAuth2 e SAML.'],
['Mesosphere DCOS', 'avaliar', 'plataformas', 's1', 'MESOSPHERE DCOS é uma plataforma baseada em Mesos que abstrai sua infraestrutura subjacente para aplicações conteinerizadas, bem como para aplicações que você não quer executar dentro do Docker. Pode ser um exagero para implantações mais modestas, mas temos começado a ver sucesso tanto com a versão comercial quanto com a versão open source. Nós particularmente gostamos do fato de que ela facilita portabilidade entre diferentes provedores de nuvem, bem como hardware dedicado, e que para tarefas conteinerizadas você não fica dependente de um framework de orquestração de contêiner. Embora upgrades possam ser um pouco mais complexos do que gostaríamos, a plataforma de maneira geral está se estabilizando.'],
['Mosquitto', 'avaliar', 'plataformas', 's2', 'Em nossa experiência—para soluções de Internet das Coisas (IoT) em que muitos dispositivos se comunicam entre si e/ou com um hub de dados central—o protocolo de conectividade MQTT provou-se eficaz. Nós também gostamos do agente MOSQUITTO MQTT. Pode não satisfazer todas as necessidades, especialmente no que diz respeito à escalabilidade, mas a sua natureza compacta e fácil configuração o tornam ideal para propósitos de desenvolvimento e testes.'],
['Nuance Mix', 'avaliar', 'plataformas', 's1', '<a href="https://developer.nuance.com/public/index.php?task=mix">Nuance Mix</a> é um framework de processamento de linguagem natural que criou a tecnologia por trás de interfaces como Dragon Speaking e a primeira versão da Siri. Esse framework suporta a criação de uma gramática que permite o usuário interagir de forma livre através da voz. A tecnologia vai se adaptando e se aprimorando através do uso e de correções. Embora ainda esteja em versão beta, é um framework que vale a pena dar uma olhada.'],
['OpenVR', 'avaliar', 'plataformas', 's1', '<a href="https://github.com/ValveSoftware/openvr">OpenVR</a> é o SDK por trás de muitos dos head-mounted displays de realidade virtual. Funciona com o Unity e sua importância deve continuar crescendo. Embora seu código não seja aberto, ele é gratuito, desde que respeitado seu licenciamento. Se pretende desenvolver um aplicativo de realidade virtual e quer que funcione no maior número possível de dispositivos, OpenVR é a melhor solução por enquanto.'],
['PlatformIO', 'avaliar', 'plataformas', 's2', 'O PLATFORMIO fornece um rico ecossistema para o desenvolvimento de aplicações relacionadas a internet das coisas, contando com compilação multiplataforma, gerenciamento de biblioteca e boa integração com IDEs existentes. O autocompletar inteligente de código e o linter de código inteligente com o terminal interno e o monitor de porta serial aumentam consideravelmente a experiência de quem desenvolve. Ele também organiza e mantém milhares de bibliotecas e fornece um gerenciador de dependência limpo com versões semânticas para facilitar o desenvolvimento de IoT. Começamos a usar o PlatformIO em alguns projetos de IoT e gostamos bastante por sua simplicidade e amplo suporte a plataformas e painéis.'],
['Tango', 'avaliar', 'plataformas', 's2', 'Assim como realidade virtual (RV), que tem uma barreira relativamente alta de entrada devido aos requisitos de hardware e ao esforço para criar mundos virtuais, realidade alternativa (RA) e realidade mista (RM), também passaram a predominar no ano passado. O jogo Pokémon Go forneceu evidências de que os smartphones normais são suficientes para criar experiências convincentes de RA/RM. TANGO é uma nova tecnologia de sensor de hardware para telefones celulares que aumenta ainda mais as possibilidades de RA/RM em telefones. Ele permite que os aplicativos adquiram medições detalhadas em 3D do ambiente em volta do usuário, para que os objetos virtuais possam ser colocados e renderizados de forma mais convincente no feed da câmera. Os primeiros telefones com a tecnologia Tango já estão disponíveis.'],
['Plataformas Conversacionais', 'avaliar', 'plataformas', 's2', 'Amazon Alexa e Google Home estão em alta; alguns até prenunciam a onipresença da interface de voz conversacional. Já estamos integrando interfaces de conversação em produtos e vendo como essa nova interação impacta a concepção de interfaces de usuário. A Alexa foi especificamente construída sem uma interface gráfica desde o início e trata a interface conversacional com o usuário como conceito de primeira classe. Mas ainda é muito cedo para acreditar na onda, e esperamos que mais grandes empresas entrem no jogo.'],
['WebVR', 'avaliar', 'plataformas', 's2', 'WEBVR é uma API experimental em JavaScript que permite o acesso a dispositivos de realidade virtual (RV) através do seu navegador. Ela vem obtendo suporte da comunidade e está disponível por meio de compilações noturnas, bem como em algumas versões de lançamento. Se você está procurando construir experiências RV em seu navegador, esse é um ótimo lugar para começar. Essa tecnologia, juntamente com ferramentas como Three.js, A-Frame, ReactVR, Argon.js e Awe.js traz experiências de RA para o navegador. A quantidade de ferramentas nessa área, juntamente com comissões de padrões da Internet, poderá ajudar a promover uma adoção mais forte de RA e RV.'],
['wit.ai', 'avaliar', 'plataformas', 's1', '<a href="https://wit.ai/">wit.ai</a> é uma plataforma SaaS que permite que desenvolvedores criem interfaces de conversação que utilizem o processamento de linguagem natural. Wit funciona tanto com texto escrito quanto falado. O sistema é gratuito para todos os usos e encoraja a criação de aplicativos de código aberto. É importante ressaltar que é necessário concordar que os dados gerados pela sua implementação podem ser utilizados para melhorar o serviço e a plataforma.'],
['CMS como plataforma', 'evitar', 'plataformas', 's3', 'O uso de Sistemas de Gerenciamento de Conteúdo (CMS) como plataforma tem gerado grandes problemas na entrega de grandes e complexos programas. É recomendado que ele seja usado como um componente da sua plataforma, em vez de tentar implementar toda a funcionalidade através dele.'],
['Gateways API muito ambiciosos', 'evitar', 'plataformas', 's1', 'Tentar desenvolver APIs de forma ambiciosa pode gerar um código extremamente difícil de testar e implementar. APIs gateways podem ser úteis no gerenciamento de conteúdos genéricos, como autenticação, mas qualquer tarefa "inteligente" como transformação de dados ou processamento de regras deve residir em aplicações e serviços que podem ser facilmente controlados.'],
['fastlane', 'adotar', 'ferramentas', 's1', 'Quem desenvolve aplicações web tem facilidade para simplificar e automatizar fluxos de trabalho diversos. Essas pessoas podem escolher dentre uma variedade de soluções para ajudar a automatizar os processos de lançamento. No entanto, ao desenvolver para dispositivos móveis, estamos lidando com dois sistemas operacionais que possuem maneiras diferentes de construir, testar, distribuir, gerar capturas de tela, assinar e distribuir aplicativos. Para ajudar a aliviar a dificuldade, nossos times adotaram o FASTLANE como a ferramenta de escolha para automatizar o processo de lançamento de aplicações iOS e Android. Usando configurações simples e pipelines múltiplos, eles podem alcançar entrega contínua para desenvolvimento móvel.'],
['Grafana', 'adotar', 'ferramentas', 's1', 'Quando técnicas modernas são combinadas, como microsserviços, DevOps e QA, times precisam de cada vez melhores sistemas de monitoramento. Simplesmente olhando gráficos de uso de disco e CPU se tornou pouco eficiente. <a href="http://grafana.org/">Grafana</a> utiliza esses dados recolhidos para criar interfaces elegantes e úteis. Uma particularidade extremamente útil é configurar escalas de tempo para que esses gráficos sejam sincronizados, permitindo que seja possível verificar a correlação com os programas em execução e os dados gravados.'],
['Airflow', 'experimentar', 'ferramentas', 's2', 'AIRFLOW é uma ferramenta para criar programaticamente, agendar e monitorar pipelines de dados. Ao tratar Gráficos Acíclicos Dirigidos (GADs) como código, ele incentiva pipelines de dados que podem ser mantidos, versáteis e testáveis. Nós alavancamos essa configuração em nossos projetos para poder criar pipelines dinâmicos que resultaram em fluxos de trabalho de dados enxutos e explícitos. Airflow facilita a definição dos seus operadores e executores e amplia a biblioteca para que ela se ajuste ao nível de abstração adequado ao seu ambiente.'],
['Cake and Fake', 'experimentar', 'ferramentas', 's2', 'Desde a sua introdução em 2005, o MSBuild tem sido o principal sistema de compilação no ecossistema .NET. No entanto, ele sofre de muitas das mesmas deficiências que já apontamos no Maven. A comunidade .NET começou a desenvolver alternativas ao MSBuild que são mais flexíveis, fáceis de manter e evoluem de forma mais fluida à medida que um projeto cresce. Duas destas alternativas são CAKE E FAKE. Cake usa uma DSL desenvolvida em C#, enquanto Fake usa F#. Cada um desses sistemas observou um crescimento significativo ao longo do último ano e provaram ser uma alternativa viável ao MSBuild para orquestrar tarefas habituais de compilação de projetos .NET.'],
['Galen', 'experimentar', 'ferramentas', 's1', 'Testar um site com layout responsivo em várias plataformas e verificar o funcionamento correto pode ser demorado e normalmente é feito manualmente. <a href="http://galenframework.com/">Galen</a> ajuda a resolver esse problema através de uma linguagem simples, que roda em cima do <a href="http://www.seleniumhq.org/">Selenium</a>, ele possibilita que você especifique expectativas para a aparência em vários formatos de tela.'],
['HashiCopr Vault', 'experimentar', 'ferramentas', 's1', 'Gerenciar "segredos" de uma forma segura está se tornando um pesadelo, principalmente em ambientes complexos, com muitas aplicações ou estruturado em microsserviços. <a href="https://github.com/hashicorp/vault">HashiCorp Vault</a> busca resolver esse dilema fornecendo mecanismos para acessar esses "segredos" através de uma interface unificada. Guardar e atualizar essas variáveis é um pouco trabalhoso, já que essas operações são feitas através de linha de comando e necessita de uma boa disciplina do time de desenvolvedores.'],
['Pa11y', 'experimentar', 'ferramentas', 's1', '<a href="http://pa11y.org/">Pa11y</a> é uma plataforma de automatização de testes que verifica a acessibilidade de uma página HTML. Para muitos sistemas, principalmente governamentais, esses testes têm um papel fundamental.'],
['Scikit-learn', 'experimentar', 'ferramentas', 's1', 'SCIKIT-LEARN não é uma ferramenta nova (está se aproximando do décimo aniversário). A novidade é a taxa de adoção de ferramentas e técnicas de aprendizagem de máquina fora da academia e de grandes empresas de tecnologia. Oferecendo um conjunto robusto de modelos e um rico conjunto de funcionalidades, o Scikit-learn desempenha um papel importante no sentido de tornar os conceitos e capacidades de aprendizagem de máquina mais acessíveis a um público mais amplo (e muitas vezes não-especialista).'],
['Frameworks fora de servidores', 'experimentar', 'ferramentas', 's2', 'O popular SERVERLESS FRAMEWORK fornece ferramentas para inicialização e implantação de aplicações sem servidor, usando primariamente o AWS Lambda e outras ofertas da AWS. O Serverless Framework fornece suporte a templates em JavaScript, Python, Java e C#, e tem uma comunidade ativa que contribui com plug-ins que estendem o framework. Como uma alternativa à AWS Lambda, o framework também suporta o projeto OpenWhisk da incubadora da Apache.'],
['Talisman', 'experimentar', 'ferramentas', 's1', '<a href="https://github.com/thoughtworks/talisman">Talisman</a> é um pré processador de commits que procura por padrões pré-definidos, validando mudanças no código antes de se fazer um push.'],
['Terraform', 'experimentar', 'ferramentas', 's1', 'Com <a href="https://www.terraform.io/">Terraform</a>, é possível gerenciar infraestruturas na nuvem através de definições declarativas, formatadas em arquivos de fácil leitura e com suporte a uma grande quantidade de provedores.'],
['Amazon Rekognition', 'avaliar', 'ferramentas', 's2', 'AMAZON REKOGNITION é uma das ferramentas de compreensão de imagens baseadas em nuvem que mencionamos em outra parte deste Radar. O que nós gostamos sobre ela é que a Amazon tomou uma abordagem um tanto quanto original para tornar os rostos anônimos para a AWS (usando GUIDs), amenizando algumas das preocupações de privacidade que surgem com o reconhecimento facial.'],
['Android-x86', 'avaliar', 'ferramentas', 's1', '<a href="http://www.android-x86.org/">Android-x86</a> é um projeto que busca executar o AOSP para plataformas x86. Utilizar essa versão pode reduzir o tempo de desenvolvimento, já que o uso de emuladores só se torna necessário em testes unitários.'],
['Bottled Water', 'avaliar', 'ferramentas', 's1', '<a href="https://github.com/confluentinc/bottledwater-pg">Bottled Water</a> é uma ferramenta que converte mudanças no PostgreSQL em eventos Kafka.'],
['Claudia', 'avaliar', 'ferramentas', 's2', 'A combinação do AWS Lambda com o Amazon API Gateway teve um grande impacto sobre como implantamos serviços e APIs. No entanto, mesmo nessa configuração sem servidor, a quantidade de configuração necessária para conectar coisas em conjunto não é trivial. CLAUDIA é uma ferramenta que automatiza a implantação de funções AWS Lambda escritas em JavaScript com configurações de gateway API associadas. Ela fornece configurações pré- determinadas razoáveis, e nossos times descobriram que ela permite que eles comecem a trabalhar rapidamente com microserviços baseados em Lambda.'],
['Clojure.spec', 'avaliar', 'ferramentas', 's1', '<a href="https://clojure.org/about/spec">Clojure.spec</a> permite que desenvolvedores estabeleçam critérios de verificação para estrutura de dados, como por exemplo os valores máximos e mínimos de uma variável. Permite gerar testes, validações, desestruturação dos dados, entre outros. É um jeito promissor de utilizar tipos e controles de variação em uma linguagem dinâmica.'],
['InSpec', 'avaliar', 'ferramentas', 's2', 'Como um negócio lida com a autonomia de times de entrega enquanto se certifica de que suas soluções implantadas são seguras e compatíveis? Como garantir que os servidores, uma vez implantados, permaneçam seguros e compatíveis ao longo de sua vida operacional? Esses são os problemas que o InSpec tenta resolver. INSPEC é uma ferramenta de testes de infraestrutura inspirada no Serverspec, mas com modificações que tornam a ferramenta mais útil para profissionais de segurança que precisam garantir a compatibilidade entre milhares de servidores. Testes individuais podem ser combinados em perfis de segurança completos e executados remotamente a partir de uma linha de comando. O InSpec é útil para desenvolvimento, mas se estende a testes em infraestruturas de produção implantadas continuamente, avançando para o QA na produção.'],
['Molecule', 'avaliar', 'ferramentas', 's2', 'MOLECULE é projetado para auxiliar no desenvolvimento e em testes dos papéis do Ansible. Ao construir uma estrutura base para executar testes dos papéis do Ansible em uma máquina virtual ou contêiner de sua escolha, não precisamos configurar nosso ambiente de teste manualmente. Molecule potencializa Vagrant, Docker e OpenStack para gerenciar máquinas virtuais/contêineres e suporta Serverspec, Testinfra ou Goss para executar testes. As etapas padrões no modelo da sequência de instalação incluem: gerenciamento de máquina virtual, Ansible linting, teste de idempotência e teste de convergência. Embora seja um projeto bastante novo, vemos um grande potencial para seu uso.'],
['Spacemacs', 'avaliar', 'ferramentas', 's2', 'Como qualquer fã de Emacs irá dizer, Emacs é mais do que um editor de texto; é uma plataforma para aplicações de mapeamento de caracteres. Ao longo dos últimos anos, tem havido vários avanços nessa plataforma, mas achamos que o SPACEMACS merece atenção especial. O Spacemacs fornece uma introdução à plataforma Emacs, com uma nova interface de usuário, camadas de personalização simplificadas e uma triagem cuidadosa de pacotes Emacs. Um dos objetivos do projeto é ser o melhor dos dois mundos, combinando a interface do usuário do Vim com a reprogramação interna do Emacs. Consideramos que as ferramentas de produtividade são uma parte vital do desenvolvimento de software eficaz e, se você não considerou Emacs por um tempo, sugerimos que você dê uma olhada em como a Spacemacs repensa essa clássica plataforma de desenvolvimento.'],
['spaCy', 'avaliar', 'ferramentas', 's2', 'SPACY é uma biblioteca de processamento de linguagem natural (PNL) escrita em Python. É uma biblioteca de alto desempenho, destinada ao uso em produção, que aplica modelos de PNL adequados para o processamento de texto que muitas vezes se confunde em emoticons e pontuações inconsistentes. Ao contrário de outros frameworks PNL, spaCy é uma biblioteca plugável e não uma plataforma. Destina-se a aplicações em produção ao invés de treinamento de modelo para pesquisa. Ela interage bem com TensorFlow e com o resto do ecossistema Python AI. Utilizamos spaCy no contexto corporativo para construir um mecanismo de pesquisa que usa consultas em linguagem humana e ajuda os usuários a tomar decisões de negócios.'],
['Spinnaker', 'avaliar', 'ferramentas', 's2', 'A Netflix abriu o código da SPINNAKER, sua plataforma de entrega contínua de microserviços. Comparada com outras plataformas de CI/CD, a Spinnaker implementa o gerenciamento de clusters e a implantação de imagens pré-criadas na nuvem como recursos de primeira classe. Ela suporta a implantação e o gerenciamento de cluster prontos para uso para vários provedores de nuvem, como Google Cloud Platform, AWS e Pivotal Cloud Foundry. Você pode integrar Spinnaker com Jenkins para executar um trabalho de compilação no Jenkins. Nós gostamos da abordagem opinativa de Spinnaker para implantar microserviços na nuvem—com exceção do fato de que os pipelines de Spinnaker são criados por meio de uma interface de usuário (UI) e não podem ser configurados como código.'],
['Testinfra', 'avaliar', 'ferramentas', 's2', 'Dado o amplo uso de ferramentas de infraestrutura nos dias de hoje, não é surpresa o aumento da adoção de infraestrutura como código pelos projetos atuais. Com essa tendência, vem a necessidade de testar esse código. Com TESTINFRA você pode testar o estado real de seus servidores configurados manualmente ou por ferramentas como Ansible, Puppet e Docker. Testinfra pretende ser um equivalente a Serverspec em Python e é escrito como um plug-in para o mecanismo de teste Pytest.'],
['Yarn', 'avaliar', 'ferramentas', 's2', 'YARN é um novo gerenciador de pacotes que substitui o fluxo de trabalho existente pelo cliente npm, permanecendo compatível com o registro npm. Com o cliente npm, podemos terminar com uma estrutura de árvore diferente no node_modules com base na ordem em que as dependências são instaladas. Essa natureza não-determinística pode causar problemas de "funciona na minha máquina". Ao quebrar as etapas de instalação em resolução, busca e vinculação, Yarn evita esses problemas usando algoritmos determinísticos e arquivos de lock, garantindo instalações consistentes. Também vimos construções significativamente mais rápidas em nosso ambiente de integração contínua pelo fato do Yarn colocar em cache todos os pacotes que baixa.'],
['Ember.js', 'adotar', 'linguagens & frameworks', 's1', 'Se pretende construir uma aplicação single-page e precisa escolher um framework para começar, <a href="http://emberjs.com/">Ember.js</a> é a solução. Permite que os desenvolvedores sejam altamente produtivos e sem surpresas desagradáveis. Além disso, ele possui uma interface de linha de comando que já vem um várias ferramentas de construção JavaScript.'],
['Python 3', 'adotar', 'linguagens & frameworks', 's1', 'A terceira versão da linguagem de programação é bem diferente da anterior. Com várias novas ferramentas, bibliotecas e configurações, ela não é compatível com a versão 2. Com isso, ela se tornou uma linguagem mais fácil de aprender e mais simples de utilizar. Se vai programar em Python, é altamente recomendável que já comece com a versão 3.'],
['ReactiveX', 'adotar', 'linguagens & frameworks', 's1', 'Desenvolver uma aplicação complexa que tem muitas conexões de rede, interações do usuário, e animações, na maioria das vezes, significa escrever um código cheio de retornos de chamada aninhadas. Esse código, às vezes chamado de callback hell (inferno de callbacks), não só é demorado e difícil de entender, mas também propenso a erros. O ReactiveX oferece uma abordagem alternativa, que é clara e concisa, para gerenciar tarefas e eventos assíncronos.'],
['Redux', 'adotar', 'linguagens & frameworks', 's1', 'Redux é uma maneira de pensar o desenvolvimento de aplicações criada pelo @dan_abramov que teve como principio optimizar a ideia do Flux. Ela foi criada para tentar optimizar alguns obstáculos que o Flux começou a enfrentar, e também veio para simplificar a implementação do mesmo. Inspirada em conceitos da linguagem funcional Elm, e de algumas bibliotecas JS como o Immutable.js, o Baobab, o RxJs e o próprio Flux, o Redux veio com alguns paradigmas interessantes e um pouco diferenciados do Flux.'],
['Avro', 'experimentar', 'linguagens & frameworks', 's2', 'AVRO é um framework para serialização de dados. Ao armazenar o esquema junto com o conteúdo da mensagem, ele incentiva a evolução deste esquema. Produtores podem editar nomes de campos, adicionar novos campos ou excluir campos existentes, e o Avro garante que os clientes continuarão a consumir as mensagens. Ter um esquema permite que cada dado seja escrito sem sobrecarga resultando em dados compactos e processamento mais rápido. Embora a troca de mensagens sem estrutura entre produtor e consumidor seja flexível, vimos times enfrentando problemas com mensagens incompatíveis nãoprocessadas na fila durante implantações. Usamos o Avro em vários projetos e recomendamos o uso apenas no envio mensagens não estruturadas.'],
['Elixir', 'experimentar', 'linguagens & frameworks', 's1', 'Elixir é uma linguagem de programação funcional, concorrente, de propósito geral que executa na máquina virtual Erlang (BEAM). Elixir compila em cima de Erlang para fornecer aplicações distribuídas, em tempo real suave, tolerante a falhas, non-stop, mas também a estende para suportar metaprogramação com macros e polimorfismo via protocolos.'],
['Enzyme', 'experimentar', 'linguagens & frameworks', 's1', 'Enzyme é uma biblioteca de utilidades para testar componentes React, tais como: shallow rendering, renderização de marcação estática, renderização completa do DOM.'],
['Hangfire', 'experimentar', 'linguagens & frameworks', 's2', 'Um problema comum no desenvolvimento de aplicativos é como programar tarefas que são executadas periodicamente fora do processo principal ou quando determinadas condições são atingidas. O problema fica mais complicado quando eventos inesperados, como desligamentos de aplicativos, ocorrem. A framework HANGFIRE, como nossos times descobriram, pode fazer isso e muito mais no ambiente .NET. O Hangfire é fácil de usar e flexível, e utiliza um estilo funcional. Particularmente interessante é a sua capacidade de salvar o estado de uma tarefa para que ele possa ser retomado quando um aplicativo é reiniciado após um bloqueio ou desligamento.'],
['Nightwatch', 'experimentar', 'linguagens & frameworks', 's2', 'NIGHTWATCH é uma framework que permite que testes de aceitação automatizados para aplicativos baseados em navegador sejam criados em JavaScript e executados em Node.js. O Nightwatch permite que os testes sejam definidos usando uma API fluente, que pode então ser executada contra um servidor Selenium/WebDriver. No caso de aplicativos de página única ou outras páginas pesadas em JavaScript, isso permite que os testes automatizados sejam criados e executados na mesma linguagem e no mesmo ambiente que a maioria do código.'],
['Phoenix', 'experimentar', 'linguagens & frameworks', 's1', 'Phoenix é um framework MVC escrito em Elixir. Para alguns desenvolvedores, é uma tecnologia tão boa e às vezes até melhor que Ruby on Rails. Embora a quantidade de bibliotecas não seja tão extensa, isso deve mudar em breve com o grande sucesso da linguagem Elixir.'],
['Quick and Nimble', 'experimentar', 'linguagens & frameworks', 's1', 'Um grande número de desenvolvedores iOS estão utilizando os frameworks <a href="https://github.com/Quick/Quick">Quick</a> e <a href="https://github.com/Quick/Nimble">Nimble</a> para os testes. Elas mostram testes de uma maneira intuitiva e com várias descrições, além de permitir testes assíncronos.'],
['Vue.js', 'experimentar', 'linguagens & frameworks', 's1', 'No mundo em constante mudança de frameworks de front-end JavaScript, um dos favoritos emergentes parece ser VUE.JS. Vue.js é uma alternativa mais leve para AngularJS. É projetada para ser uma biblioteca muito flexível—e menos opinativa—que oferece um conjunto de ferramentas para a construção de interfaces web interativas em torno de conceitos como modularidade, componentes e fluxo de dados reativos. Possui uma curva de aprendizagem baixa, o que a torna interessante para quem está aprendendo a desenvolver. Observe, porém, que Vue.js não é uma framework completa; tem como foco apenas a camada de visualização e, portanto, é fácil de integrar com outras bibliotecas ou projetos existentes.'],
['Angular 2', 'avaliar', 'linguagens & frameworks', 's2', 'Quando se trata de ANGULAR 2, vemos mensagens distintas. Ao longo do ano passado, algumas equipes da ThoughtWorks usaram o Angular 2 com sucesso e o consideram uma escolha sólida. No entanto, Angular 2 é uma reescrita, não uma evolução de AngularJS, e mudar de AngularJS para Angular 2 não é muito diferente de mudar de AngularJS para outro framework. Visto que, na nossa experiência, há concorrentes superiores como React.js, Ember.js e Vue.js, ainda estamos hesitantes em dar a Angular 2 uma forte recomendação. Queremos ressaltar, no entanto, que não se trata de uma escolha ruim, especialmente se você adotou TypeScript.'],
['Caffe', 'avaliar', 'linguagens & frameworks', 's2', 'O CAFFE é uma biblioteca de código aberto para aprendizagem profunda criada pelo Berkeley Vision and Learning Center. Concentra-se principalmente em redes convolucionais para aplicações de visão computacional. Caffe é uma escolha sólida e popular para tarefas relacionadas à visão computacional e você pode baixar muitos modelos bem-sucedidos feitos por usuários do Caffe Model Zoo para produtividade imediata. Assim como Keras, Caffe é uma API com base Python. Em Keras, no entanto, modelos e componentes são objetos criados diretamente em código Python, enquanto modelos Caffe são descritos por arquivos de configuração Protobuf. As duas abordagens tem seus prós e contras, e a conversão entre as duas também é possível.'],
['DeepLearning.scala', 'avaliar', 'linguagens & frameworks', 's2', 'DEEPLEARNING.SCALA é um conjunto de ferramentas de aprendizagem profunda de código aberto em Scala criado por colegas na ThoughtWorks. Esse projeto tem nos animado porque ele usa programação funcional diferenciável para criar e compor redes neurais; uma pessoa desenvolvedora simplesmente escreve código em Scala com tipos estáticos. O DeepLearning.scala atualmente suporta tipos básicos como float, double, matrizes N-dimensionais aceleradas por GPU, bem como tipos de dados algébricos. Esperamos com ansiedade futuras versões do conjunto de ferramentas que promete suportar funções de ordem superior e treinamento distribuído no Spark.'],
['ECMAScript 2017', 'avaliar', 'linguagens & frameworks', 's1', 'A versão 2017 do ECMAScript acrescentou várias melhorias notórias na linguagem. Navegadores devem adotar essa nova tecnologia até o verão de 2017, mas o compilador JavaScript <a href="https://www.thoughtworks.com/radar/tools/babel">Babel</a> já suporta essas novas tecnologias. Para quem usa bastante o JavaScript, é recomendado adicionar Babel na automação do seu Build.'],
['Instana', 'avaliar', 'linguagens & frameworks', 's2', 'INSTANA é mais um estreante no povoado espaço de gerenciamento de desempenho de aplicativos. O fato de que ele foi construído do zero para as arquiteturas nativas de nuvem diferencia Instana de muitos de seus concorrentes. Os recursos incluem descoberta dinâmica, rastreamento distribuído e saúde do serviço, além da capacidade de "mudar o tempo" de visualização da sua infraestrutura para o momento em que ocorreu um incidente. Resta saber se este produto pode ganhar junto à variedade de projetos de código aberto— como Consul, Prometheus e as implementações do OpenTracing–que fazem a mesma coisa; no entanto, vale a pena analisar se você precisa de uma solução fora da caixa.'],
['JuMP', 'avaliar', 'linguagens & frameworks', 's1', '<a href="https://github.com/JuliaOpt/JuMP.jl">JuMP</a> é uma linguagem de otimização matemática para <a href="http://julialang.org/">Julia</a>. Benefícios de utilizar JuMP estão nas técnicas de diferenciação automáticas, computação de derivadas através do modo reverso e ainda é possível implementar as próprias funções em Julia.'],
['Keras', 'avaliar', 'linguagens & frameworks', 's2', 'KERAS é uma interface de alto nível em Python para a construção de redes neurais. Criada por um engenheiro do Google, Keras possui código aberto e funciona tanto com TensorFlow quanto com Theano. Ela fornece uma interface surpreendentemente simples para criar poderosos algoritmos de aprendizagem profunda para treinar em CPUs ou GPUs. Keras é bem projetada tendo modularidade, simplicidade e extensibilidade em mente. Ao contrário de bibliotecas como Caffe, Keras suporta arquiteturas de rede mais gerais, tais como redes recorrentes, tornando-a de forma geral mais útil para análise de texto, PLN e aprendizagem de máquinas em geral. Se a visão computacional, ou qualquer outro ramo especializado de aprendizagem de máquina, é a sua principal preocupação, Caffe pode ser uma escolha acertada. No entanto, se você procura aprender uma framework simples mas poderosa, Keras deve ser a sua escolha.'],
['Knet.jl', 'avaliar', 'linguagens & frameworks', 's2', 'KNET.JL é uma framework de aprendizagem profunda da Universidade Koç implementada em Julia por Deniz Yuret e colaboradores. Ao contrário dos compiladores de geração de gradientes, como Theano e TensorFlow, que forçam os usuários a entrar em uma minilinguagem restrita, o Knet permite a definição e o treinamento de modelos de aprendizado de máquina usando a plena potência e expressividade de Julia. O Knet utiliza grafos computacionais dinâmicos gerados em tempo de execução para a diferenciação automática de praticamente qualquer código Julia. Nós realmente gostamos do suporte de operações de GPU por meio do tipo KnetArray, e caso você não tenha acesso a uma GPU, a equipe por trás do Knet também mantém uma Amazon Machine Image (AMI) pré-configurada para que você possa avaliá-lo na nuvem.'],
['Kotlin', 'avaliar', 'linguagens & frameworks', 's2', 'A linguagem de programação KOTLIN está em muitas das nossas listas de coisas para avaliar esse ano, e algumas pessoas já a usaram com sucesso em produção. É uma linguagem JVM de código aberto da JetBrains. Quem desenvolve em Swift para dispossitivos móveis gosta, visto que é sintaticamente mais próxima de Swift e igualmente concisa. As pessoas que desenvolvem em Java têm apreciado sua interoperabilidade perfeita com a linguagem e com as ferramentas Java e achado mais fácil de aprender do que Scala. Kotlin suporta conceitos de programação funcional, mas com menos recursos do que Scala. Algumas pessoas que gostam de tipos estáticos com o compilador capturando defeitos de ponteiros nulos perceberam que estavam escrevendo menos testes para estes casos.'],
['Physical Web', 'avaliar', 'linguagens & frameworks', 's1', 'O conceito de <a href="">Physical Web</a> criada pela Google é bem simples - dispositivos transmitem uma URL -, mas as possibilidades, imensas. Basicamente, é um jeito de tomar notas do mundo físico, tornando objetos e locais mais digitais.'],
['PostCSS', 'avaliar', 'linguagens & frameworks', 's2', 'POSTCSS é uma framework JavaScript baseada em Node.js para operar em uma representação abstrata baseada em árvore de sintaxe de documentos CSS com um rico ecossistema de plug-ins. Muitas vezes considerado incorretamente como um pré-processador (como SaaS ou Less), descobrimos que o verdadeiro poder do PostCSS vem do número de coisas que podem ser feitas com o rico conjunto de plug-ins, que inclui verificação de estilo (o plug-in stylelint), compilação cruzada (o plug-in sugarss), name-mangling para evitar a colisão de seletor (o plug-in modules), geração de código CSS padrão (o autoprefixer plug-in), minificação e muitos outros. Apesar dos diferentes níveis de maturidade dos plug-ins, o PostCSS permanece uma framework simples e poderosa para o tratamento de CSS como uma linguagem completa para o desenvolvimento de front-end.'],
['Spring Cloud', 'avaliar', 'linguagens & frameworks', 's2', 'Times construindo sistemas compostos por microsserviços precisam pensar sobre técnicas de coordenação tais como descoberta de serviços, balaceamento de carga, circuit breakers e health check. Muitas dessas técnicas exigem que os times configurem ferramentas, o que nem sempre é trivial. O projeto SPRING CLOUD provê ferramentas para que pessoas desenvolvedoras utilizem essas técnicas no ambiente Spring. Essas ferramentas suportam Consul, ZooKeeper e a stack Netflix OSS, todas ferramentas que gostamos. De maneira simples, é mais fácil fazer a coisa certa com esse conjunto de ferramentas. Embora ainda tenhamos nossa preocupação usual com Spring, visto que muito da complexidade é escondida, você pode considerar Spring Cloud se já estiver no ecosistema e precisar resolver esses tipos de problemas.'],
['Three.js', 'avaliar', 'linguagens & frameworks', 's1', 'Embora os headsets de realidade virtual/aumentada estejam na mora, há casos em que essas tecnologias sejam mais úteis em dispositivos como telefones e tablets. Para isso tornar isso possível, o <a href="">Three.js</a> foi criado, que em sua essência é uma ferramenta de visualização e renderização 3D baseada em JavaScript.'],
['WebRTC', 'avaliar', 'linguagens & frameworks', 's1', '<a href="https://webrtc.org/">WebRTC</a> é uma nova tendência de padronização de comunicação em tempo real entre navegadores WEB. Alguns desenvolvedores acreditam que essa ferramenta pode ser o princípío da interação colaborativa entre Realidade Aumentada/Realidade Virtual na WEB.'],
['AngularJS', 'evitar', 'linguagens & frameworks', 's1', 'Embora <a href="https://angularjs.org/">AngularJS</a> tenha ajudado a revolucionar o mundo de aplicações de uma única página, é recomendado utilizar outras tecnologias, como <a href="https://www.emberjs.com/">Ember</a> e <a href="https://facebook.github.io/react/">React</a>, principalmente se alinhadas com <a href="http://redux.js.org/">Redux</a>.']




]





// which will need to be converted to an array of objects...
const rawData = rawDataTable.slice(1).map(function(x) {
    // likely a better way to do this ?
    var response = {}
    for (var i = 0; i < x.length; i++)  {
        response[rawDataTable[0][i]] = x[i];
    }
    return response
})

const _ = {
    map: require('lodash/map'),
    uniqBy: require('lodash/uniqBy'),
    capitalize: require('lodash/capitalize'),
    each: require('lodash/each')
};

const InputSanitizer = require('./inputSanitizer');
const Radar = require('../models/radar');
const Quadrant = require('../models/quadrant');
const Ring = require('../models/ring');
const Blip = require('../models/blip');
const GraphingRadar = require('../graphing/radar');
const MalformedDataError = require('../exceptions/malformedDataError');
const ContentValidator = require('./contentValidator');
const ExceptionMessages = require('./exceptionMessages');

const InlineSheet = function () {
    var self = {};

    self.build = function () {
        var columnNames = Object.keys(rawData[0])

        var contentValidator = new ContentValidator(columnNames);
        contentValidator.verifyContent();
        contentValidator.verifyHeaders();

        var all = rawData;
        var blips = _.map(all, new InputSanitizer().sanitize);
        var rings = _.map(_.uniqBy(blips, 'ring'), 'ring');
        var ringMap = {};
        var maxRings = 4;

        _.each(rings, function (ringName, i) {
            if (i == maxRings) {
                throw new MalformedDataError(ExceptionMessages.TOO_MANY_RINGS);
            }
            ringMap[ringName] = new Ring(ringName, i);
        });

        var quadrants = {};
        _.each(blips, function (blip) {
            if (!quadrants[blip.quadrant]) {
                quadrants[blip.quadrant] = new Quadrant(_.capitalize(blip.quadrant));
            }
            quadrants[blip.quadrant].add(new Blip(blip.name, ringMap[blip.ring], blip.type, blip.topic, blip.description))
        });

        var radar = new Radar();
        _.each(quadrants, function (quadrant) {
            radar.addQuadrant(quadrant)
        });

        var size = (window.innerHeight - 133) < 620 ? 620 : window.innerHeight - 133;
        new GraphingRadar(size, radar).init().plot();
    };

    return self;
};

module.exports = InlineSheet;
